### ISSUE TITLE
Can't run appliction using info from README

### ISSUE THREAD

**Issue by solar-vibez-development** [rolandgeider/wger#277] opened 2016-03-25 08:58 UTC
I'm trying to install development version from Git under Ubuntu 15.10.
Python 3.4
`npm list` shows "bower@1.7.7"

Commands I've used:
`sudo apt-get install python3-dev python-virtualenv nodejs nodejs-legacy npm libjpeg8-dev zlib1g-dev`
`virtualenv --python python3 venv-django`
`source venv-django/bin/activate`
`git clone https://github.com/rolandgeider/wger.git`
`cd wger`
`pip install -r requirements_devel.txt`
`sudo npm install -g bower`
`npm install bower`
`invoke --root wger bootstrap_wger`
After running the last command, I get an error:

> *** Creating settings file at /home/denis/.config/wger
Traceback (most recent call last):
  File "/home/denis/Development/projects/venv-django/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/invoke/program.py", line 270, in run
    self.execute()
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/invoke/executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/invoke/tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "/home/denis/Development/projects/wger/wger/tasks.py", line 101, in bootstrap_wger
    setup_django_environment(settings_path)
  File "/home/denis/Development/projects/wger/wger/tasks.py", line 385, in setup_django_environment
    django.setup()
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/django/__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/denis/Development/projects/venv-django/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/denis/.config/wger/settings.py", line 4, in <module>
    from wger.settings_global import *
ImportError: No module named 'wger'

After this, I ran:
`python setup.py build`
`python setup.py install`
`invoke --root wger bootstrap_wger`

But seeing this error:
> djangobower.exceptions.BowerNotInstalled: Bower not installed, read instruction here - http://bower.io/

Project structure is:
wger
--build
--dist
--docs
--extras
--node_modules
----bower
----.bin
-------bower
--wger
--wger.egg-info
--.git

I'm new in Python and it's env, so maybe I'm doing something wrong.

**Comment by rolandgeider** [comment] 2016-03-25 09:27
Thanks for the detailed report :), I'll take a look right away

**Comment by rolandgeider** [comment] 2016-03-25 10:38
You are right, there is something not working here.

**Comment by rolandgeider** [comment] 2016-03-27 14:06
@solar-vibez-development I found what was causing this, we are playing with the sys.path because of some differences between the pypi package and the devel version. As a workaround, you can try this (basically, just call the invoke command with explicit paths):

```bash
apt-get install python3-dev python-virtualenv nodejs nodejs-legacy npm libjpeg8-dev zlib1g-dev
virtualenv --python python3 venv-django
source venv-django/bin/activate
git clone https://github.com/rolandgeider/wger.git
cd wger
pip install -r requirements_devel.txt

invoke --root wger create_settings \
       --settings-path /home/wger/wger/settings.py \
       --database-path /home/wger/wger/database.sqlite
invoke --root wger bootstrap_wger \
       --settings-path /home/wger/wger/settings.py \
       --no-start-server
python manage.py runserver
```

**Comment by rolandgeider** [comment] 2016-03-27 14:13
@rolandgeider: this is becasue of ``sys.path = sys.path[1:]`` in tasks.py

**Comment by alokhan** [comment] 2016-04-05 20:18
Hi,

I have used the command with explicit paths but I still get the message from 
```
wger.settings_global import *
ImportError: No module named 'wger'
```

I am using Fedora 23 :)

**Comment by rolandgeider** [comment] 2016-04-05 20:26
@alokhan, well it seems I just got plans for the week :-S

**Comment by alokhan** [comment] 2016-04-09 19:25
When if comment the line sys.path = sys.path[1:] 

I get this error: 

`Traceback (most recent call last):
  File "/home/alo/venv-django/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/home/alo/venv-django/lib/python3.4/site-packages/invoke/program.py", line 270, in run
    self.execute()
  File "/home/alo/venv-django/lib/python3.4/site-packages/invoke/program.py", line 379, in execute
    executor.execute(*self.tasks)
  File "/home/alo/venv-django/lib/python3.4/site-packages/invoke/executor.py", line 114, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/alo/venv-django/lib/python3.4/site-packages/invoke/tasks.py", line 113, in __call__
    result = self.body(*args, **kwargs)
  File "/home/alo/git/wger/wger/tasks.py", line 101, in bootstrap_wger
    setup_django_environment(settings_path)
  File "/home/alo/git/wger/wger/tasks.py", line 385, in setup_django_environment
    django.setup()
  File "/home/alo/venv-django/lib/python3.4/site-packages/django/__init__.py", line 15, in setup
    from django.utils.log import configure_logging
  File "/home/alo/venv-django/lib/python3.4/site-packages/django/utils/log.py", line 11, in <module>
    from django.core import mail
  File "/home/alo/venv-django/lib/python3.4/site-packages/django/core/mail/__init__.py", line 14, in <module>
    from django.core.mail.message import (
  File "/home/alo/venv-django/lib/python3.4/site-packages/django/core/mail/message.py", line 8, in <module>
    from email import (
  File "/home/alo/git/wger/wger/email/__init__.py", line 18, in <module>
    from wger import get_version
ImportError: No module named 'wger'
`

**Comment by alokhan** [comment] 2016-04-10 13:21
Ok i have go it working but I had to manually install bower package using:
./manage.py bower install

then manually start the server with :
./manage.py runserver

**Comment by rolandgeider** [comment] 2016-04-11 11:33
@alokhan strange that you had to manually do that step, this should be taken care by the invoke command.

I think it would be a good idea to write a development docker image with fedora, then it'll be easier to check that there are no problems with the installation in the future.

**Comment by alelevinas** [comment] 2016-04-25 10:32
Hi, i've been trying to install the development version from Git under Ubuntu 14.04

I'm having the same problem as alokhan with the **exact same outputs**.

I've tried everything in this post but nothing works. Even when I execute 

```./manage.py bower install```
and the output is 
```BowerNotInstalled: Bower not installed, read instruction here - http://bower.io/```

even though Bower IS installed version bower@1.7.9

Did you think of another workarround this problem??

**Comment by SR-G** [comment] 2016-04-26 14:18
On my side, i can't run the application with docker as suggested in the README.md
- "wger/apache" does not seems to exist anymore (i've just found wger/base and/or wger/devel)
- when starting with the provided docker command and wger/base image, the container does not start and i have no logs under docker logs.

**Comment by rolandgeider** [comment] 2016-04-26 16:56
Hi all! Sorry for not answering (or doing anything about this) earlier, I was/kind of still am on vacation and hadn't had time.

I have reverted the changes that caused the import errors and my tests on docker & co are positive. If you want to test this just pull from master and try to install it again. You might want to delete the repo to clear it of incorrectly installed node folders, settings files and so.

@SR-G I will also check why there are no docker images, I should have received a notification if the build process failed, but don't know how often this happens, probably only when the dockerfile itself changes.

And of course, thanks for trying all kind of different and crazy things :)

**Comment by rolandgeider** [comment] 2016-04-26 18:30
The Docker images should be fixed now as well. I'm leaving this issue open for some days, in case some detail creeps up.

**Comment by SR-G** [comment] 2016-04-26 18:45
I can confirm that the docker wger/apache image is back (and working fine). Thanks.

**Comment by rolandgeider** [comment] 2016-04-26 19:02
Great, thanks for testing

**Closed** 2016-05-03 22:24 UTC
Labels: bug

**Comment by alelevinas** [comment] 2016-05-09 19:09
Sorry for disappearing, everything works fine.

Gonna look for something to contribute on.

**Comment by rolandgeider** [comment] 2016-05-10 09:58
@alelevinas :+1: You might want to take a look at the bitesize issues, but if you don't find any fun things to do, just ask
